services:
  - type: web
    name: clipsens-api
    runtime: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT